# basic options
title: Gary's first test blog
author: Gary G.
email: your-email@domain.com
description: A wonderful blog site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: architect
